<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">

<!-- base line property -->
<xacro:property name="base_link_length" value="0.6"/>
<xacro:property name="base_link_weigth" value="0.4"/>
<xacro:property name="base_link_height" value="0.2"/>
<!-- wheel property-->
<xacro:property name="wheel_row" value="1.57"/>
<xacro:property name="wheel_length" value="0.05"/>
<xacro:property name="wheel_radius" value="0.15"/>
<!-- wheel_joint property -->
<xacro:property name="wheel_joint_x" value="0.2"/>
<xacro:property name="wheel_joint_y" value="0.2"/>
<xacro:property name="wheel_joint_z" value="0.2"/>
<xacro:property name="wheel_axis" value="1"/>
<xacro:property name="effort" value="10"/>
<xacro:property name="velocity" value="5"/>
<xacro:property name="upper" value="3.14"/>
<xacro:property name="lower" value="3.14"/>
<!--property of moment inertial-->
<xacro:property name="mass" value="0.5"/>
<xacro:property name="ixx" value="0.01"/>
<xacro:property name="iyy" value="0.01"/>
<xacro:property name="izz" value="0.01"/>
<link name="dummy" >

</link>
<joint name="dummy_base_link" type="fixed">
	<parent link="dummy"/>
	<child link="base_link"/>
</joint>
<material name="black">
	<color rgba="0.1 0.1 0.2 1"/>
</material>
<link name="base_link">
	<visual>
		<origin rpy="0 0 0" xyz="0 0 0"/>
		<geometry>
			<box size="${base_link_length} ${base_link_weigth} ${base_link_height}"/>
		</geometry>
		<material name="black"/>
	</visual>
	<collision>
		<origin rpy="0 0 0" xyz="0 0 0"/>
		<geometry>
			<box size="${base_link_length} ${base_link_weigth} ${base_link_height}"/>
		</geometry>
		<material name="black"/>
	</collision>
	<inertial>
		<mass value="${mass}"/>
		<origin xyz=" 0 0 0 "/>
		<inertia ixx="${ixx}" ixy="0" ixz="0" iyy="${iyy}" iyz="0" izz="${izz}"/>
	</inertial>
</link>

<link name="back_left_wheel">
	<visual>
		<origin rpy="${wheel_row} 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
		</geometry>
	</visual>
	<collision>
		<origin rpy="${wheel_row} 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
		</geometry>
	</collision>
	<inertial>
		<mass value="${mass}"/>
		<origin xyz=" 0 0 0 "/>
		<inertia ixx="${ixx}" ixy="0" ixz="0" iyy="${iyy}" iyz="0" izz="${izz}"/>
	</inertial>
</link>
<joint name="joint_back_left_wheel" type="continuous">
	<origin xyz="${-wheel_joint_x} ${-wheel_joint_y} 0"/>
	<parent link="base_link"/>
	<child link="back_left_wheel"/>
	<axis xyz="0 ${wheel_axis} 0"/>
	<limit effort="${effort}" velocity="${velocity}" lower="${lower}" upper="${upper}"/>
</joint>


<link name="back_right_wheel">
	<visual>
		<origin rpy="${-wheel_row} 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
		</geometry>
	</visual>
	<collision>
		<origin rpy="${-wheel_row} 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
		</geometry>
	</collision>
	<inertial>
		<mass value="${mass}"/>
		<origin xyz=" 0 0 0 "/>
		<inertia ixx="${ixx}" ixy="0" ixz="0" iyy="${iyy}" iyz="0" izz="${izz}"/>
	</inertial>
</link>
<joint name="joint_back_right_wheel" type="continuous">
	<origin xyz="${-wheel_joint_x} ${wheel_joint_y} 0"/>
	<parent link="base_link"/>
	<child link="back_right_wheel"/>
	<axis xyz="0 ${wheel_axis} 0"/>
	<limit effort="${effort}" velocity="${velocity}" lower="${lower}" upper="${upper}"/>
	
</joint>
<link name="front_right_wheel">
	<visual>
		<origin rpy="${wheel_row} 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
		</geometry>
	</visual>
	<collision>
		<origin rpy="${wheel_row} 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${-wheel_length}" radius="${wheel_radius}"/>
		</geometry>
	</collision>
	<inertial>
		<mass value="${mass}"/>
		<origin xyz=" 0 0 0 "/>
		<inertia ixx="${ixx}" ixy="0" ixz="0" iyy="${iyy}" iyz="0" izz="${izz}"/>
	</inertial>
</link>
<joint name="joint_front_right_wheel" type="continuous">
	<origin xyz="${wheel_joint_x} ${wheel_joint_y} 0"/>
	<parent link="base_link"/>
	<child link="front_right_wheel"/>
	<axis xyz="0 ${wheel_axis} 0"/>
	<limit effort="${effort}" velocity="${velocity}" lower="${lower}" upper="${upper}"/>
	
</joint>

<link name="front_left_wheel">
	<visual>
		<origin rpy="${-wheel_row} 0 0" xyz="0 0 0"/>>
		<geometry>
			<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
		</geometry>
	</visual>
	<collision>
		<origin rpy="${-wheel_row} 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${-wheel_length}" radius="${wheel_radius}"/>
		</geometry>
	</collision>
	<inertial>
		<mass value="${mass}"/>
		<origin xyz=" 0 0 0 "/>
		<inertia ixx="${ixx}" ixy="0" ixz="0" iyy="${iyy}" iyz="0" izz="${izz}"/>
	</inertial>

</link>
<joint name="joint_front_left_wheel" type="continuous">
	<origin xyz="${wheel_joint_x} ${-wheel_joint_y} 0"/>
	<parent link="base_link"/>
	<child link="front_left_wheel"/>
	<axis xyz="0 ${wheel_axis} 0"/>
	<limit effort="${effort}" velocity="${velocity}" lower="${lower}" upper="${upper}"/>
</joint>

 <!-- laser_scan -->
<link name="laser_scan">
	<visual>
	<origin rpy="0 0 0" xyz="0 0 0"/>
		<geometry>	
			<box size="0.04 0.04 0.04"/>
		</geometry>
	</visual>
	<collision>
	<origin rpy="0 0 0" xyz="0 0 0"/>
		<geometry>	
			<box size="0.06 0.04 0.04"/>
		</geometry>
	</collision>
</link>
<joint name="base_link_laser_scan" type="fixed">
	<origin xyz="0.32 0 0.1"/>
	<parent link="base_link"/>
	<child link="laser_scan"/>
</joint>

<!-- camera_scan-->
<link name="camera_scan">
	<visual>
	<origin rpy="0 0 0" xyz="0 0 0"/>
		<geometry>
			<box size="0.02 0.08 0.04"/>
		</geometry>
	</visual>
</link>
<joint name="base_link_camera_scan" type="fixed">
	<origin xyz="0.3 0 0.0"/>
	<parent link="base_link"/>
	<child link="camera_scan"/>
</joint>

<!-- imu_link-->
<link name="imu_scan">
	<visual>
	<origin rpy="0 0 0" xyz="0 0 0"/>
		<geometry>
			<box size="0.1 0.1 0.06"/>		
		</geometry>	
	</visual>
</link>
<joint name="base_link_IMU_scan" type="fixed">
	<origin xyz="0 0 0.1"/>
	<parent link="base_link"/>
	<child link="imu_scan"/>
</joint>


<gazebo reference="base_link">
	<material>Gazebo/Gray</material>
	<turnGravityOff>false</turnGravityOff>
</gazebo>
<gazebo reference="front_right_wheel">
	<material>Gazebo/Orange</material>
	<turnGravityOff>false</turnGravityOff>
</gazebo>
<gazebo reference="front_left_wheel">
	<material>Gazebo/Orange</material>
	<turnGravityOff>false</turnGravityOff>
</gazebo>
<gazebo reference="back_right_wheel">
	<material>Gazebo/Orange</material>
	<turnGravityOff>false</turnGravityOff>
</gazebo>
<gazebo reference="back_left_wheel">
	<material>Gazebo/Orange</material>
	<turnGravityOff>false</turnGravityOff>
</gazebo>
<gazebo>
	<plugin  name="differential_drive_robot" filename="libgazebo_ros_diff_drive.so">
		<robotNamespace>/</robotNamespace>
		<commandTopic>cmd_vel</commandTopic>
		<odometryTopic>odom</odometryTopic>
		<odometryFrame>odom</odometryFrame>
		<robotBaseFrame>base_link</robotBaseFrame>
		<publishWheelTF>false</publishWheelTF>
		<publishOdomTF>true</publishOdomTF>
		<publishWheelJointState>false</publishWheelJointState>
		<legacyMode>true</legacyMode>
		
		<wheelSeparation>${base_link_length}</wheelSeparation>
		<wheelDiameter>${2*wheel_radius}</wheelDiameter>
		<wheelAcceleration>1.0</wheelAcceleration>
		<wheelTorque>20.0</wheelTorque>
		<updateRate>10.0</updateRate>
		<leftJoint>joint_front_left_wheel</leftJoint>
		<rightJoint>joint_front_right_wheel</rightJoint>
		<left_joint>joint_back_left_wheel</left_joint>
		<right_joint>joint_back_right_wheel</right_joint>
	</plugin>
</gazebo>
<!-- plugin laser scan-->
<gazebo reference="laser_scan">
	<material>Gazebo/Red</material>
	<turnGravityOff>true</turnGravityOff>
	<sensor type="ray" name="laser_scan_sensor">
		<pose>0 0.04 0 0 0 0</pose>		
		<visualize>true</visualize>
		<update_rate>10.0</update_rate>	
		<ray>
			<scan>
				<horizontal>
					<sample>500</sample>
					<resolution>1.0</resolution>
					<min_angle>-1.57</min_angle>
					<max_angle>1.57</max_angle>
				</horizontal>
			</scan>
			<range>
				<min>0.1</min>
				<max>10</max>
				<resolution>1</resolution>
			</range>
		</ray>
		<plugin name="laser_scanner" filename="libgazebo_ros_laser.so">
			<topicName>/scan</topicName>
			<frameName>laser_scan</frameName>
		</plugin >
	</sensor>	
</gazebo>

<!-- camera plugin -->
  <gazebo reference="camera_scan">
  	<material>Gazebo/Green</material>
	<turnGravityOff>true</turnGravityOff>
    <sensor type="camera" name="camera1">
      <update_rate>30.0</update_rate>
      <camera name="head">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>800</width>
          <height>800</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <!-- Noise is sampled independently per pixel on each frame.
               That pixel's noise value is added to each of its color
               channels, which at that point lie in the range [0,1]. -->
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>rrbot/camera1</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera_scan</frameName>
        <hackBaseline>0.07</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
  </gazebo>


<!-- camera plugin 
<gazebo>
    <plugin name="imu_plugin" filename="libgazebo_ros_imu.so">
      <alwaysOn>true</alwaysOn>
      <bodyName>imu_scan</bodyName>
      <topicName>imu</topicName>
      <serviceName>imu_service</serviceName>
      <gaussianNoise>0.0</gaussianNoise>
      <updateRate>20.0</updateRate>
    </plugin>
</gazebo>-->

<gazebo reference="imu_scan">
 <material>Gazebo/Yellow</material>
 <turnGravityOff>true</turnGravityOff>
    <gravity>true</gravity>
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <visualize>true</visualize>
      <topic>__default_topic__</topic>
      <plugin name="imu_plugin" filename="libgazebo_ros_imu_sensor.so" >
        <topicName>imu</topicName>
        <bodyName>imu_scan</bodyName>
        <updateRateHZ>10.0</updateRateHZ>
        <gaussianNoise>0.0</gaussianNoise>
        <xyzOffset>0 0 0</xyzOffset>
        <rpyOffset>0 0 0</rpyOffset>
        <frameName>imu_scan</frameName>
        <initialOrientationAsReference>false</initialOrientationAsReference>
      </plugin>
      <pose>0 0 0 0 0 0</pose>
    </sensor>
  </gazebo> 
</robot>
